"""add order address

Revision ID: 66b6a87d2f1a
Revises: abd224bdc31a
Create Date: 2026-04-28 21:55:47.891360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b6a87d2f1a'
down_revision: Union[str, Sequence[str], None] = 'abd224bdc31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=2), nullable=True))
    op.add_column('orders', sa.Column('shipping_zip_code', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_zip_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###
