"""add shipping number and complement

Revision ID: 810bf99208a0
Revises: de219f563197
Create Date: 2026-04-29 21:24:02.598034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810bf99208a0'
down_revision: Union[str, Sequence[str], None] = 'de219f563197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_number', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shipping_complement', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_complement')
    op.drop_column('orders', 'shipping_number')
    # ### end Alembic commands ###
