"""add customizable options

Revision ID: 8b78b90541cb
Revises: c2a06808930b
Create Date: 2026-04-28 16:01:42.281914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b78b90541cb'
down_revision: Union[str, Sequence[str], None] = 'c2a06808930b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_options', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('seller_product_specs', sa.Column('is_customizable', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('seller_product_specs', sa.Column('customization_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_product_specs', 'customization_options')
    op.drop_column('seller_product_specs', 'is_customizable')
    op.drop_column('orders', 'product_options')
    # ### end Alembic commands ###
