"""Add email verification fields to users table

Revision ID: a2daf945552e
Revises: e457311db20f
Create Date: 2026-04-28 14:05:27.117629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2daf945552e'
down_revision: Union[str, Sequence[str], None] = 'e457311db20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'project_iterations', ['approved_iteration_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verification_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'email_verified')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
