"""add images urls

Revision ID: c2a06808930b
Revises: a2daf945552e
Create Date: 2026-04-28 14:41:18.059562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a06808930b'
down_revision: Union[str, Sequence[str], None] = 'a2daf945552e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_reference_images',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_reference_images_order_id'), 'order_reference_images', ['order_id'], unique=False)
    op.create_table('seller_product_images',
    sa.Column('product_spec_id', sa.UUID(), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_spec_id'], ['seller_product_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_product_images_product_spec_id'), 'seller_product_images', ['product_spec_id'], unique=False)
    op.add_column('project_iterations', sa.Column('image_key', sa.String(length=500), nullable=True))
    op.drop_column('project_iterations', 'image_url')
    op.drop_column('project_iterations', 'image_path')
    op.add_column('seller_profiles', sa.Column('logo_key', sa.String(length=500), nullable=True))
    op.add_column('seller_profiles', sa.Column('banner_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_key')
    op.drop_column('seller_profiles', 'banner_key')
    op.drop_column('seller_profiles', 'logo_key')
    op.add_column('project_iterations', sa.Column('image_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('project_iterations', sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('project_iterations', 'image_key')
    op.drop_index(op.f('ix_seller_product_images_product_spec_id'), table_name='seller_product_images')
    op.drop_table('seller_product_images')
    op.drop_index(op.f('ix_order_reference_images_order_id'), table_name='order_reference_images')
    op.drop_table('order_reference_images')
    # ### end Alembic commands ###
